# /plugman debug true/false -s (save to config)
debug: false

# PlugMan requires Java 7 or above to function properly, only set this to true if you know you are on Java 7 (or above) but the version check fails.
skip-java-version-check: false

# Should we use Metrics stat collection?
use-metrics: true

# Determine which type of updater we should use.
# Available options:
#   - download: this is the default mode and will automatically download the plugin and have it ready for the next restart.
#   - check: this checks for a new version and alerts you if a new version is available.
updater-type: download