name: PlugMan
main: com.rylinaux.plugman.PlugMan
version: 2.0.0
description: Plugin Manager For Bukkit Plugins
author: rylinaux
commands:
  plugman:
    description: Manage plugins
    usage: /<command>